#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
LOCAL_DIR="$ROOT_DIR/local"
CERT_DIR="$LOCAL_DIR/config/certs"
CERT_CRT="$CERT_DIR/local.crt"
CERT_KEY="$CERT_DIR/local.key"
COMPOSE_FILE="$LOCAL_DIR/docker-compose.yml"
HOST_TAG="# generated by pnpm local:hosts"

HOSTS=(
  "testnet.test"
  "api.testnet.test"
  "auth.testnet.test"
  "rafiki-backend.testnet.test"
  "rafiki-frontend.testnet.test"
  "boutique.testnet.test"
  "api.boutique.testnet.test"
  "rafiki-card-service.testnet.test"
  "mockgatehub.testnet.test"
)

compose() {
  docker compose -f "$COMPOSE_FILE" "$@"
}

reload_traefik_if_running() {
  if compose ps --status running --services traefik 2>/dev/null | grep -q '^traefik$'; then
    echo "Reloading Traefik to pick up trusted cert..."
    compose restart traefik
  else
    echo "Traefik is not running; skipping reload."
  fi
}

run_certs() {
  mkdir -p "$CERT_DIR"

  if [[ -f "$CERT_CRT" && -f "$CERT_KEY" && "${FORCE_CERTS:-0}" != "1" ]]; then
    echo "TLS cert already exists. Reusing it (set FORCE_CERTS=1 to regenerate)."
    return
  fi

  if [[ "${HEADLESS:-0}" == "1" ]]; then
    openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
      -keyout "$CERT_KEY" -out "$CERT_CRT" \
      -subj "/CN=testnet.test/O=Interledger/C=US" \
      -config "$LOCAL_DIR/config/san.cnf"
  else
    openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
      -keyout "$CERT_KEY" -out "$CERT_CRT" \
      -config "$LOCAL_DIR/config/san.cnf"
  fi
}

run_all() {
  run_certs
  compose up -d

  echo
  echo "Please open these ALL of these URLs in your browser and accept the self-signed certificates:"
  echo "  - https://mockgatehub.testnet.test/health"
  echo "  - https://api.testnet.test/health"
  echo "  - https://api.boutique.testnet.test/products"
  echo "  - https://rafiki-frontend.testnet.test"
  echo "  - https://rafiki-backend.testnet.test/healthz"
  echo "  - https://auth.testnet.test/healthz"
  echo "  - https://testnet.test"
  echo "  - https://boutique.testnet.test"
}

run_hosts() {
  sudo sed -i.bak '/# generated by make hosts/d' /etc/hosts
  sudo sed -i.bak '/# generated by pnpm local:hosts/d' /etc/hosts
  sudo rm -f /etc/hosts.bak

  for host in "${HOSTS[@]}"; do
    echo "127.0.0.1 $host $HOST_TAG" | sudo tee -a /etc/hosts >/dev/null
  done
}

run_trust_macos() {
  run_certs
  sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain "$CERT_CRT"
  reload_traefik_if_running
}

run_trust_linux() {
  run_certs
  sudo cp "$CERT_CRT" /usr/local/share/ca-certificates/interledger-testnet-local.crt
  sudo update-ca-certificates

  rm -rf "$HOME/.pki/nssdb"
  mkdir -p "$HOME/.pki/nssdb"
  certutil -d sql:"$HOME/.pki/nssdb" -N --empty-password
  certutil -d sql:"$HOME/.pki/nssdb" -A -t "C,," -n "testnet.test" -i "$CERT_CRT"

  reload_traefik_if_running
}

run_trust() {
  run_certs

  if [[ "$(uname -s)" == "Darwin" ]]; then
    run_trust_macos
  else
    run_trust_linux
  fi
}

run_help() {
  cat <<'EOF'
pnpm run <command>

e.g. pnpm local:all

local:help                 Show this help message
local:all                  Start full local stack (with Traefik)
local:all-nowatch          Alias for local:all
local:build                Build docker images for local stack
local:rebuild              Force rebuild docker images (no cache)
local:rafiki-assets        Run Rafiki asset setup script
local:down                 Stop the local stack
local:reset                Stop stack and remove volumes
local:hosts                Add testnet host aliases to /etc/hosts (requires sudo)
local:certs                Generate TLS cert if missing (set FORCE_CERTS=1 to regenerate)
local:trust                Trust local TLS certificate (auto-detect OS, reloads Traefik)
local:trust:macos          Trust certificate on macOS
local:trust:linux          Trust certificate on Debian-based Linux (reloads Traefik)
EOF
}

case "${1:-help}" in
  help)
    run_help
    ;;
  all)
    run_all
    ;;
  certs)
    run_certs
    ;;
  hosts)
    run_hosts
    ;;
  trust)
    run_trust
    ;;
  trust-macos)
    run_trust_macos
    ;;
  trust-linux)
    run_trust_linux
    ;;
  *)
    echo "Unknown command: $1" >&2
    echo "Run: pnpm local:help" >&2
    exit 1
    ;;
esac
