#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
LOCAL_DIR="$ROOT_DIR/local"
CERT_DIR="$LOCAL_DIR/config/certs"
TESTNET_CERT_CRT="$CERT_DIR/local.crt"
TESTNET_CERT_KEY="$CERT_DIR/local.key"
BOUTIQUE_CERT_CRT="$CERT_DIR/boutique.crt"
BOUTIQUE_CERT_KEY="$CERT_DIR/boutique.key"
COMPOSE_FILE="$LOCAL_DIR/docker-compose.yml"
HOST_TAG="# generated by pnpm local:hosts"
TESTNET_CERT_NICKNAME="interledger-testnet-local"
BOUTIQUE_CERT_NICKNAME="interledger-boutique-local"

HOSTS=(
  "testnet.test"
  "api.testnet.test"
  "auth.testnet.test"
  "rafiki-backend.testnet.test"
  "rafiki-frontend.testnet.test"
  "boutique.test"
  "api.boutique.test"
  "rafiki-card-service.testnet.test"
  "mockgatehub.testnet.test"
)

# If .env does not exist then create it with touch
if [[ ! -f "$LOCAL_DIR/.env" ]]; then
  touch "$LOCAL_DIR/.env"
fi

compose() {
  docker compose -f "$COMPOSE_FILE" \
    --env-file "$LOCAL_DIR/.env.local" \
    --env-file "$LOCAL_DIR/.env" \
    "$@"
}

reload_traefik_if_running() {
  echo "Checking Traefik status..."
  if compose ps --status running --services traefik 2>/dev/null | grep -q '^traefik$'; then
    echo "Reloading Traefik to pick up trusted cert..."
    compose restart traefik
    echo "Traefik restarted."
  else
    echo "Traefik is not running; skipping reload."
  fi
}

run_certs() {
  echo "Preparing TLS certificate directory: $CERT_DIR"
  mkdir -p "$CERT_DIR"

  local has_testnet_cert=false
  local has_boutique_cert=false
  [[ -f "$TESTNET_CERT_CRT" && -f "$TESTNET_CERT_KEY" ]] && has_testnet_cert=true
  [[ -f "$BOUTIQUE_CERT_CRT" && -f "$BOUTIQUE_CERT_KEY" ]] && has_boutique_cert=true

  if [[ "$has_testnet_cert" == true && "$has_boutique_cert" == true && "${FORCE_CERTS:-0}" != "1" ]]; then
    echo "TLS certs already exist. Reusing them (set FORCE_CERTS=1 to regenerate)."
    echo "  testnet cert : $TESTNET_CERT_CRT"
    echo "  testnet key  : $TESTNET_CERT_KEY"
    echo "  boutique cert: $BOUTIQUE_CERT_CRT"
    echo "  boutique key : $BOUTIQUE_CERT_KEY"
    return
  fi

  if [[ "${FORCE_CERTS:-0}" == "1" ]]; then
    echo "FORCE_CERTS=1 detected. Regenerating certificate and key."
  else
    echo "No existing TLS certificate found. Generating a new one."
  fi

  echo "Generating certificates using SAN configs:"
  echo "  - $LOCAL_DIR/config/san-testnet.cnf"
  echo "  - $LOCAL_DIR/config/san-boutique.cnf"

  if [[ "${HEADLESS:-0}" == "1" ]]; then
    echo "HEADLESS=1: using non-interactive OpenSSL subject values."
    openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
      -keyout "$TESTNET_CERT_KEY" -out "$TESTNET_CERT_CRT" \
      -subj "/CN=*.testnet.test/O=Interledger/C=US" \
      -config "$LOCAL_DIR/config/san-testnet.cnf"

    openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
      -keyout "$BOUTIQUE_CERT_KEY" -out "$BOUTIQUE_CERT_CRT" \
      -subj "/CN=*.boutique.test/O=Interledger/C=US" \
      -config "$LOCAL_DIR/config/san-boutique.cnf"
  else
    echo "HEADLESS not set: OpenSSL may prompt depending on your local config."
    openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
      -keyout "$TESTNET_CERT_KEY" -out "$TESTNET_CERT_CRT" \
      -config "$LOCAL_DIR/config/san-testnet.cnf"

    openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
      -keyout "$BOUTIQUE_CERT_KEY" -out "$BOUTIQUE_CERT_CRT" \
      -config "$LOCAL_DIR/config/san-boutique.cnf"
  fi

  echo "Generated TLS assets:"
  echo "  testnet cert : $TESTNET_CERT_CRT"
  echo "  testnet key  : $TESTNET_CERT_KEY"
  echo "  boutique cert: $BOUTIQUE_CERT_CRT"
  echo "  boutique key : $BOUTIQUE_CERT_KEY"
}

run_all() {
  echo "Starting full local stack setup..."
  run_certs
  echo "Bringing up docker compose services from: $COMPOSE_FILE"
  compose up -d
}

run_hosts() {
  echo "Updating /etc/hosts entries for testnet domains..."
  echo "Removing previously managed entries..."
  sudo sed -i.bak '/# generated by make hosts/d' /etc/hosts
  sudo sed -i.bak '/# generated by pnpm local:hosts/d' /etc/hosts
  sudo rm -f /etc/hosts.bak

  for host in "${HOSTS[@]}"; do
    echo "Adding host mapping: 127.0.0.1 $host"
    echo "127.0.0.1 $host $HOST_TAG" | sudo tee -a /etc/hosts >/dev/null
  done

  echo "Host aliases updated successfully."
}

run_trust_macos() {
  echo "Applying certificate trust for macOS system keychain..."
  run_certs
  sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain "$TESTNET_CERT_CRT"
  echo "macOS trust entry installed for: $TESTNET_CERT_CRT"
  sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain "$BOUTIQUE_CERT_CRT"
  echo "macOS trust entry installed for: $BOUTIQUE_CERT_CRT"
  reload_traefik_if_running
}

run_trust_linux() {
  echo "Applying certificate trust for Linux..."
  run_certs

  echo "Installing cert into system CA store: /usr/local/share/ca-certificates/interledger-testnet-local.crt"
  sudo cp "$TESTNET_CERT_CRT" /usr/local/share/ca-certificates/interledger-testnet-local.crt
  echo "Installing cert into system CA store: /usr/local/share/ca-certificates/interledger-boutique-local.crt"
  sudo cp "$BOUTIQUE_CERT_CRT" /usr/local/share/ca-certificates/interledger-boutique-local.crt
  echo "Refreshing system CA certificates..."
  sudo update-ca-certificates

  if ! command -v certutil >/dev/null 2>&1; then
    echo "certutil not found; install 'libnss3-tools' to auto-trust certs in Chrome/Chromium NSS stores."
    reload_traefik_if_running
    return
  fi

  local nss_dbs=(
    "$HOME/.pki/nssdb"
    "$HOME/snap/chromium/current/.pki/nssdb"
    "$HOME/snap/google-chrome/current/.pki/nssdb"
    "$HOME/.var/app/com.google.Chrome/config/google-chrome/.pki/nssdb"
    "$HOME/.var/app/org.chromium.Chromium/config/chromium/.pki/nssdb"
  )
  local nss_pass_file
  nss_pass_file="$(mktemp)"
  printf '\n' >"$nss_pass_file"

  echo "Importing cert into NSS databases when accessible..."

  for db in "${nss_dbs[@]}"; do
    # Always manage the default NSS DB; only manage app-specific DBs when present.
    if [[ "$db" != "$HOME/.pki/nssdb" && ! -d "$db" ]]; then
      echo "Skipping NSS DB (not present): $db"
      continue
    fi

    echo "Processing NSS DB: $db"
    mkdir -p "$db"

    if [[ ! -f "$db/cert9.db" || ! -f "$db/key4.db" || ! -f "$db/pkcs11.txt" ]]; then
      echo "Initializing NSS DB with empty password: $db"
      if ! certutil -d sql:"$db" -N --empty-password >/dev/null 2>&1; then
        echo "Skipping NSS DB (failed to initialize): $db"
        continue
      fi
    fi

    certutil -d sql:"$db" -D -n "$TESTNET_CERT_NICKNAME" -f "$nss_pass_file" >/dev/null 2>&1 || true
    certutil -d sql:"$db" -D -n "$BOUTIQUE_CERT_NICKNAME" -f "$nss_pass_file" >/dev/null 2>&1 || true

    if certutil -d sql:"$db" -A -t "C,," -n "$TESTNET_CERT_NICKNAME" -i "$TESTNET_CERT_CRT" -f "$nss_pass_file" >/dev/null 2>&1; then
      echo "Trusted testnet cert in NSS DB: $db"
    else
      echo "Skipping testnet cert in NSS DB (password-protected or inaccessible): $db"
    fi

    if certutil -d sql:"$db" -A -t "C,," -n "$BOUTIQUE_CERT_NICKNAME" -i "$BOUTIQUE_CERT_CRT" -f "$nss_pass_file" >/dev/null 2>&1; then
      echo "Trusted boutique cert in NSS DB: $db"
    else
      echo "Skipping boutique cert in NSS DB (password-protected or inaccessible): $db"
    fi
  done

  echo "Cleaning up temporary NSS password file."
  rm -f "$nss_pass_file"

  reload_traefik_if_running
}

run_trust() {
  echo "Applying trust configuration for local TLS certificate..."
  run_certs

  if [[ "$(uname -s)" == "Darwin" ]]; then
    echo "Detected OS: macOS"
    run_trust_macos
  else
    echo "Detected OS: Linux"
    run_trust_linux
  fi
}

run_help() {
  cat <<'EOF'
pnpm run <command>

e.g. pnpm local:all

local:help                 Show this help message
local:all                  Start full local stack (with Traefik)
local:all-nowatch          Alias for local:all
local:build                Build docker images for local stack
local:rebuild              Force rebuild docker images (no cache)
local:rafiki-assets        Run Rafiki asset setup script
local:down                 Stop the local stack
local:reset                Stop stack and remove volumes
local:hosts                Add testnet host aliases to /etc/hosts (requires sudo)
local:certs                Generate TLS cert if missing (set FORCE_CERTS=1 to regenerate)
local:trust                Trust local TLS certificate (auto-detect OS, reloads Traefik)
local:trust:macos          Trust certificate on macOS
local:trust:linux          Trust certificate on Debian-based Linux (reloads Traefik)
EOF
}

case "${1:-help}" in
  help)
    run_help
    ;;
  all)
    run_all
    ;;
  certs)
    run_certs
    ;;
  hosts)
    run_hosts
    ;;
  trust)
    run_trust
    ;;
  trust-macos)
    run_trust_macos
    ;;
  trust-linux)
    run_trust_linux
    ;;
  *)
    echo "Unknown command: $1" >&2
    echo "Run: pnpm local:help" >&2
    exit 1
    ;;
esac
