name: 'File Change Detection'
description: 'Detect which projects file has been change for running its own checks'

runs:
  using: 'composite'
  outputs:
    wallet-back: ${{ steps.wallet-back.outputs.WALLET_BACK }}
    wallet-front: ${{ steps.wallet-front.outputs.WALLET_FRONT }}
    boutique-front: ${{ steps.boutique-front.outputs.BOUTIQUE_FRONT }}
    boutique-back: ${{ steps.boutique-back.outputs.BOUTIQUE_BACK }}

  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
    - name: Get changed files
      id: changed-files
      run: |
        if ${{ github.event_name == 'pull_request' }}; then
            echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
        else
            echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
        fi
    - name: Change wallet back changed files
      id: wallet-back
      run: |
        echo 'HELLO WORLD'
        for file in ${{ steps.changed-files.outputs.changed_files }}; do
             if [[ $file == *"wallet/backend"* ]]; then 
               echo "WALLET_BACK='true'" >> $GITHUB_OUTPUT
             fi;
        done;

    - name: Change wallet front changed files
      id: wallet-front
      run: |
        for file in ${{ steps.changed-files.outputs.changed_files }}; do
             if [[ $file == *"wallet/frontend"* ]]; then 
               echo "WALLET_FRONT='true'" >> $GITHUB_OUTPUT
             fi;
        done;

    - name: Change wallet front changed files
      id: boutique-front
      run: |
        for file in ${{ steps.changed-files.outputs.changed_files }}; do
             if [[ $file == *"boutique/frontend"* ]]; then 
               echo "WALLET_FRONT='true'" >> $GITHUB_OUTPUT
             fi;
        done;

    - name: Change wallet front changed files
      id: boutique-back
      run: |
        for file in ${{ steps.changed-files.outputs.changed_files }}; do
             if [[ $file == *"boutique/backend"* ]]; then 
               echo "WALLET_FRONT='true'" >> $GITHUB_OUTPUT
             fi;
        done;

#  hessam:
#    name: WALLET - Build frontend
#    runs-on: ubuntu-latest
#    needs: detect-changes
#    steps:
#      - name: Test Variable2
#        run: |
#          echo "${{needs.detect-changes.outputs.wallet-back}}"
#          if [ ${{needs.detect-changes.outputs.wallet-back || 'false'}} != "workflows" ]; then
#             echo "you fucked up"
#          exit 1
#          fi
#      - uses: actions/checkout@v4
#      - uses: ./.github/workflows/setup
#      - run: pnpm wallet:frontend build
