CREATE USER backend WITH PASSWORD 'backend';
CREATE DATABASE backend;
ALTER DATABASE backend OWNER TO backend;

CREATE USER auth WITH PASSWORD 'auth';
CREATE DATABASE auth;
ALTER DATABASE auth OWNER TO auth;
