export enum MessageType {
  MONEY_RECEIVED = 'MONEY_RECEIVED',
  MONEY_SENT = 'MONEY_SENT',
  MONEY_SENT_SHOP = 'MONEY_SENT_SHOP'
}

export enum MessageErrorType {
  EXCEPTION = 'EXCEPTION',
  ERROR_MINOR_CURRENCY_UNITS = 'ERROR_MINOR_CURRENCY_UNITS'
}
