'package: wallet/backend':
  - packages/wallet/backend/**/*
  - packages/shared/telemetry/**/*
'package: wallet/frontend':
  - packages/wallet/frontend/**/*
  - packages/shared/telemetry/**/*
'package: boutique/backend': packages/boutique/backend/**/*
'package: boutique/frontend': packages/boutique/frontend/**/*

'type: ci':
  - .github/*
  - .github/**/*

'type: documentation':
  - '**/*.md'

'type: source':
  - packages/wallet/backend/src/**/*
  - packages/wallet/frontend/src/**/*
  - packages/boutique/backend/src/**/*
  - packages/boutique/backend/src/**/*

'type: test': packages/**/*.test.ts

'type: docker': docker/*
