name: Feature request
description: Submit a feature request
title: '[FEATURE REQUEST] '
labels: ['discussion: idea', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! Please fill out this form as completely as possible. If this issue has a `needs approval` label, please do not start coding yet. Wait until a core member approves the feature request by removing this label.

  - type: textarea
    id: describe
    attributes:
      label: Describe the feature you would like to request
      description: A clear and concise description of what you want and what your use case is.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you would like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
